name: Build socat

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Cygwin
      uses: actions/checkout@v2

    - name: Install Cygwin
      run: |
        choco install cygwin -y
        refreshenv

    - name: Build socat
      run: |
        # 进入 Cygwin 环境
        cygwin/bin/bash -l -c "cd /path/to/socat && ./configure && make"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: socat
        path: /path/to/socat/bin/socat
