name: Build Socat

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install MSYS2
        run: |
          choco install msys2 -y
          refreshenv

      - name: Install build dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-make

      - name: Build Socat
        run: |
          git clone https://github.com/theshdowaura/socat.git
          cd socat
          ./configure
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: socat
          path: socat/socat.exe
