name: Build Socat

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install Cygwin
        run: |
          choco install cygwin -y
          refreshenv

      - name: Build Socat
        run: |
          git clone https://github.com/theshdowaura/socat.git
          cd socat
          ./configure
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: socat
          path: socat/socat.exe
